services:
  apache:
    build: ./docker/php-apache
    ports:
    - 8080:80
    volumes:
    - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
    - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=stark_industries
      - MYSQL_USER=stark
      - MYSQL_PASSWORD=stark
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
